on:
  push:
    branches:
      - main
      - master

name: epib6o7 website

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      # - name: install fonts and font system deps
      #   run: |
      #     brew install pkg-config
      #     brew install harfbuzz fribidi
      #     brew tap homebrew/cask-fonts
      #     brew install --cask font-ibm-plex
      #     brew install --cask font-roboto
      #     brew install --cask font-roboto-slab
      #     brew install --cask font-roboto-mono

      - name: Install packages
        run: |
          R -e 'install.packages("renv")' -e 'install.packages(c("pacman","remotes","bookdown","bslib","downlit","xml2","extrafont", "dplyr","tidyr","knitr","rmarkdown","ggplot2","swirl","DT","rio","forcats","sf","colorspace","extrafont","ggrepel","patchwork","mosaic","ggpubr","kableExtra","socviz","gapminder"))'
          R -e 'remotes::install_github("OI-Biostat/oi_biostat_data")' -e 'remotes::install_github("OpenIntroStat/openintro")' -e 'remotes::install_github("wilkelab/cowplot")' -e 'remotes::install_github("clauswilke/colorblindr")' -e 'remotes::install_github("clauswilke/dviz.supp")'
          R -e 'renv::restore()'

      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"

      - name: Commit results
        run: |
          cp ghpagescname _book/CNAME
          cd _book
          git init
          git add .
          git commit -m 'update book'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:gh-pages --force

